/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.EquipmentControl;
import Logic.Equipment;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Diego
 */
public class EditEquipmentForm extends javax.swing.JPanel {

    EquipmentControl equipmentControl;
    
    public EditEquipmentForm() {
        initComponents();
        equipmentControl = new EquipmentControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oldValuesLabel = new javax.swing.JLabel();
        oldSerieTextField = new javax.swing.JTextField();
        oldCodeLabel = new javax.swing.JLabel();
        oldNameLabel = new javax.swing.JLabel();
        oldSerielNumber = new javax.swing.JLabel();
        oldDescriptionLabel = new javax.swing.JLabel();
        oldStateLabel = new javax.swing.JLabel();
        oldCodeTextField = new javax.swing.JTextField();
        oldNameTextField = new javax.swing.JTextField();
        editEquipmentLabel = new javax.swing.JLabel();
        newSerieTextField = new javax.swing.JTextField();
        newNameLabel = new javax.swing.JLabel();
        newStateComboBox = new javax.swing.JComboBox<>();
        newSerielNumber = new javax.swing.JLabel();
        newDescriptionLabel = new javax.swing.JLabel();
        newStateLabel = new javax.swing.JLabel();
        newNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editButtom = new javax.swing.JButton();
        oldStateTextField = new javax.swing.JTextField();
        newCodeLabel = new javax.swing.JLabel();
        newCodeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        oldDescriptionTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        newDescriptionTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 433));

        oldValuesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        oldValuesLabel.setText("Valores Antiguos");

        oldSerieTextField.setEditable(false);
        oldSerieTextField.setBackground(new java.awt.Color(204, 204, 204));

        oldCodeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oldCodeLabel.setText("Codigo");

        oldNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oldNameLabel.setText("Articulo");

        oldSerielNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oldSerielNumber.setText("Numero de serie");

        oldDescriptionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oldDescriptionLabel.setText("Descripcion");

        oldStateLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oldStateLabel.setText("Estado");

        oldCodeTextField.setEditable(false);
        oldCodeTextField.setBackground(new java.awt.Color(204, 204, 204));

        oldNameTextField.setEditable(false);
        oldNameTextField.setBackground(new java.awt.Color(204, 204, 204));

        editEquipmentLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editEquipmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editEquipmentLabel.setText("Editar Equipo");
        editEquipmentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newNameLabel.setText("Articulo");

        newStateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Prestado", "Atrasado" }));

        newSerielNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newSerielNumber.setText("Numero de serie");

        newDescriptionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newDescriptionLabel.setText("Descripcion");

        newStateLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newStateLabel.setText("Estado");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Nuevos Valores");

        editButtom.setText("Editar");
        editButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtomActionPerformed(evt);
            }
        });

        oldStateTextField.setEditable(false);
        oldStateTextField.setBackground(new java.awt.Color(204, 204, 204));

        newCodeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        newCodeLabel.setText("Codigo");

        newCodeTextField.setEditable(false);
        newCodeTextField.setBackground(new java.awt.Color(204, 204, 204));

        oldDescriptionTextArea.setEditable(false);
        oldDescriptionTextArea.setColumns(20);
        oldDescriptionTextArea.setRows(5);
        oldDescriptionTextArea.setLineWrap(true);
        oldDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(oldDescriptionTextArea);

        newDescriptionTextArea.setColumns(20);
        newDescriptionTextArea.setRows(5);
        newDescriptionTextArea.setLineWrap(true);
        newDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(newDescriptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editEquipmentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oldSerielNumber)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oldNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(oldCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(oldDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(oldStateLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(oldValuesLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newSerielNumber)
                            .addComponent(newNameLabel)
                            .addComponent(newCodeLabel)
                            .addComponent(newDescriptionLabel)
                            .addComponent(newStateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editEquipmentLabel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldValuesLabel)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldCodeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldSerielNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldDescriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldStateLabel))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newStateLabel)
                                    .addComponent(newStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newCodeLabel)
                                    .addComponent(newCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newNameLabel)
                                    .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newSerielNumber)
                                    .addComponent(newSerieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newDescriptionLabel))
                                .addGap(44, 44, 44)))
                        .addComponent(editButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtomActionPerformed
        // TODO add your handling code here:
        String numberEquipment;
        String nameEquipment;
        String serieEquipment;
        String descriptionEquipment;
        String stateEquipment;

        if(newNameTextField.getText().length()>0 && newSerieTextField.getText().length()>0 && newDescriptionTextArea.getText().length()>0){
            
            numberEquipment=oldCodeTextField.getText();
            nameEquipment=newNameTextField.getText();
            serieEquipment=newSerieTextField.getText();
            descriptionEquipment=newDescriptionTextArea.getText();
            stateEquipment=(String)newStateComboBox.getSelectedItem();

            int numFilas = equipmentControl.updateEquipment(numberEquipment,nameEquipment, serieEquipment, descriptionEquipment, stateEquipment);

            System.out.println ("Filas "+ numFilas);
            if (numFilas == 1){
                JOptionPane.showMessageDialog(null, "Equipo actualizado exitosamente");
                loadEditEquipment();
            }
            else {
                JOptionPane.showMessageDialog(null, "Ocurrio un problema al actualizar el Equipo");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos");
        }
    }//GEN-LAST:event_editButtomActionPerformed

    public void limpiar_texto(JPanel panel){
        for(int i = 0; panel.getComponents().length > i; i++){
            if(panel.getComponents()[i] instanceof JTextField){
                ((JTextField)panel.getComponents()[i]).setText("");
            }
            else if(panel.getComponents()[i] instanceof JPasswordField){
                ((JPasswordField)panel.getComponents()[i]).setText("");
            }
        }
    }
    
    public void loadEditEquipment(){
        EditEquipment editarEquipment = new EditEquipment();
        editarEquipment.setSize(639,483);
        editarEquipment.setLocation(0,0);
        
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editarEquipment);
    }
    
    public void setValues(String code, String name, String serial, String description, String state){
        
        newCodeTextField.setText(code);
        newNameTextField.setText(name);
        newSerieTextField.setText(serial);
        newDescriptionTextArea.setText(description);
        
        oldCodeTextField.setText(code);
        oldNameTextField.setText(name);
        oldSerieTextField.setText(serial);
        oldDescriptionTextArea.setText(description);
        oldStateTextField.setText(state);
        //stateEquipment=(String)newStateComboBox.getSelectedItem();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButtom;
    private javax.swing.JLabel editEquipmentLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel newCodeLabel;
    private javax.swing.JTextField newCodeTextField;
    private javax.swing.JLabel newDescriptionLabel;
    private javax.swing.JTextArea newDescriptionTextArea;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JTextField newSerieTextField;
    private javax.swing.JLabel newSerielNumber;
    public static javax.swing.JComboBox<String> newStateComboBox;
    private javax.swing.JLabel newStateLabel;
    private javax.swing.JLabel oldCodeLabel;
    private javax.swing.JTextField oldCodeTextField;
    private javax.swing.JLabel oldDescriptionLabel;
    private javax.swing.JTextArea oldDescriptionTextArea;
    private javax.swing.JLabel oldNameLabel;
    private javax.swing.JTextField oldNameTextField;
    private javax.swing.JTextField oldSerieTextField;
    private javax.swing.JLabel oldSerielNumber;
    private javax.swing.JLabel oldStateLabel;
    private javax.swing.JTextField oldStateTextField;
    private javax.swing.JLabel oldValuesLabel;
    // End of variables declaration//GEN-END:variables
}
