/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.UserControl;
import Logic.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class EditProfileForm extends javax.swing.JPanel {
    User sessionUser;
    UserControl userControl;
    /**
     * Creates new form EditProfile
     */
    public EditProfileForm(User sessionUser) {
        initComponents();
        this.sessionUser=sessionUser;
        userControl=new UserControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editEquipmentLabel = new javax.swing.JLabel();
        newPhoneTextField = new javax.swing.JTextField();
        nameLabel3 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        nameLabel5 = new javax.swing.JLabel();
        nameLabel6 = new javax.swing.JLabel();
        oldPasswordField = new javax.swing.JPasswordField();
        newPasswordFieldAgain = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();
        editButtom = new javax.swing.JButton();
        backButtom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        editEquipmentLabel.setBackground(new java.awt.Color(255, 255, 255));
        editEquipmentLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editEquipmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editEquipmentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarUsuarioTitle.png"))); // NOI18N
        editEquipmentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        newPhoneTextField.setPreferredSize(new java.awt.Dimension(30, 30));

        nameLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel3.setText("Teléfono");

        nameLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel4.setText("Contraseña Antigua");

        nameLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel5.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel5.setText("Repita la Contraseña");

        nameLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel6.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel6.setText("Contraseña Nueva");

        oldPasswordField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        oldPasswordField.setPreferredSize(new java.awt.Dimension(30, 30));

        newPasswordFieldAgain.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        newPasswordFieldAgain.setPreferredSize(new java.awt.Dimension(30, 30));

        newPasswordField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        newPasswordField.setPreferredSize(new java.awt.Dimension(30, 30));

        editButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GuardarButtom.png"))); // NOI18N
        editButtom.setBorderPainted(false);
        editButtom.setContentAreaFilled(false);
        editButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtomActionPerformed(evt);
            }
        });

        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CancelarButton.png"))); // NOI18N
        backButtom.setBorderPainted(false);
        backButtom.setContentAreaFilled(false);
        backButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editEquipmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel5)
                    .addComponent(nameLabel4)
                    .addComponent(nameLabel3)
                    .addComponent(nameLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newPhoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPasswordFieldAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editEquipmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel3)
                    .addComponent(newPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel4)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel6)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel5)
                    .addComponent(newPasswordFieldAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtomActionPerformed
        // TODO add your handling code here:
        String newPhone;
        
        if(newPhoneTextField.getText().length()>0){

            newPhone=newPhoneTextField.getText();

            int numFilas = userControl.updateProfile(newPhone, sessionUser.getCode());

            System.out.println ("Filas "+ numFilas);
            if (numFilas == 1){
                JOptionPane.showMessageDialog(null, "Teléfono actualizado exitosamente");
                newPhoneTextField.setText("");
            }
            else {
                JOptionPane.showMessageDialog(null, "Ocurrio un problema al actualizar el Usuario");
            }
        }
        
        if(oldPasswordField.getText().length()>0 && newPasswordField.getText().length()>0 && newPasswordFieldAgain.getText().length()>0){
            if(oldPasswordField.getText().equals(sessionUser.getPassword())){
                if(newPasswordField.getText().equals(newPasswordFieldAgain.getText())){
                    String newPassword = new String(newPasswordField.getPassword());
                    userControl.updatePassword(newPassword,sessionUser.getCode());
                    JOptionPane.showMessageDialog(null, "Contraseña Actualizada Correctamente");
                    oldPasswordField.setText("");
                    newPasswordField.setText("");
                    newPasswordFieldAgain.setText("");
                }
                else{JOptionPane.showMessageDialog(null, "Las constraseñas nuevas no coinciden");}
            }
            else{JOptionPane.showMessageDialog(null, "La contraseña Antigua es incorrecta");}
        }
        
        if(oldPasswordField.getText().length()==0 || newPasswordField.getText().length()==0 || newPasswordFieldAgain.getText().length()==0 && newPhoneTextField.getText().length()==0){
            JOptionPane.showMessageDialog(null, "No se ingresó la información completa, no se hará ningún cambio en la contraseña");
        }
        
        
        
        

    }//GEN-LAST:event_editButtomActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        // TODO add your handling code here:
        MenuProfile menuProfile = new MenuProfile(sessionUser);
        menuProfile.setSize(639,483);
        menuProfile.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(menuProfile);
    }//GEN-LAST:event_backButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JButton editButtom;
    private javax.swing.JLabel editEquipmentLabel;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel nameLabel6;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPasswordField newPasswordFieldAgain;
    private javax.swing.JTextField newPhoneTextField;
    private javax.swing.JPasswordField oldPasswordField;
    // End of variables declaration//GEN-END:variables
}
