/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.UserControl;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class EditUserForm extends javax.swing.JPanel {
    UserControl userControl;
    /**
     * Creates new form EditUserForm
     */
    public EditUserForm() {
        initComponents();
        userControl = new UserControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editEquipmentLabel = new javax.swing.JLabel();
        newLastNameTextField = new javax.swing.JTextField();
        newCodeTextField = new javax.swing.JTextField();
        newFirstNameTextField = new javax.swing.JTextField();
        newEmailTextField = new javax.swing.JTextField();
        nameLabel14 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        nameLabel15 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        nameLabel16 = new javax.swing.JLabel();
        nameLabel17 = new javax.swing.JLabel();
        nameLabel18 = new javax.swing.JLabel();
        newPhoneTextField = new javax.swing.JTextField();
        newIdentificationTextField = new javax.swing.JTextField();
        editButtom = new javax.swing.JButton();
        newTypeIDComboBox = new javax.swing.JComboBox<>();
        newChargeComboBox = new javax.swing.JComboBox<>();
        newStateComboBox = new javax.swing.JComboBox<>();
        backButtom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        editEquipmentLabel.setBackground(new java.awt.Color(255, 255, 255));
        editEquipmentLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editEquipmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editEquipmentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarUsuarioTitle.png"))); // NOI18N
        editEquipmentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newLastNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        newCodeTextField.setEditable(false);
        newCodeTextField.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        newCodeTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        newFirstNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        newEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        nameLabel14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel14.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel14.setText("Estado");

        nameLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel2.setText("Email");

        nameLabel15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel15.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel15.setText("Identificacion");

        nameLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel3.setText("Telefono");

        nameLabel16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel16.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel16.setText("Cargo");

        nameLabel17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel17.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel17.setText("Nombres");

        nameLabel18.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel18.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel18.setText("Apellidos");

        newPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        newIdentificationTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        editButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GuardarButtom.png"))); // NOI18N
        editButtom.setBorderPainted(false);
        editButtom.setContentAreaFilled(false);
        editButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtomActionPerformed(evt);
            }
        });

        newTypeIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo de Estudiante", "Cedula de Ciudadanìa", "Tarjeta de Identidad", "Cedula de Extranjerìa"}));
        newTypeIDComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newTypeIDComboBox.setPreferredSize(new java.awt.Dimension(28, 27));

        newChargeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miembro", "Coordinador de Equipos", "Lider de Proyecto", "Director de Laboratorio", "Administrador" }));
        newChargeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newChargeComboBox.setPreferredSize(new java.awt.Dimension(28, 27));

        newStateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Bloqueado"  }));
        newStateComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStateComboBox.setPreferredSize(new java.awt.Dimension(28, 27));

        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CancelarButton.png"))); // NOI18N
        backButtom.setBorderPainted(false);
        backButtom.setContentAreaFilled(false);
        backButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editEquipmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel15)
                            .addComponent(nameLabel17)
                            .addComponent(nameLabel2)
                            .addComponent(nameLabel3)
                            .addComponent(nameLabel16)
                            .addComponent(nameLabel18)
                            .addComponent(nameLabel14)
                            .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newEmailTextField)
                                    .addComponent(newPhoneTextField)
                                    .addComponent(newChargeComboBox, 0, 215, Short.MAX_VALUE)
                                    .addComponent(newLastNameTextField)
                                    .addComponent(newStateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newIdentificationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(newFirstNameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newTypeIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editEquipmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel15)
                        .addComponent(newIdentificationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newTypeIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel18)
                    .addComponent(newLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel2)
                    .addComponent(newEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel3)
                    .addComponent(newPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel16)
                    .addComponent(newChargeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtomActionPerformed
        // TODO add your handling code here:
        String code;
        String identification;
        String firstName;
        String lastName;
        String email;
        String charge;
        String typeID;
        String phone;
        String state;

        if(newIdentificationTextField.getText().length()>0 && newFirstNameTextField.getText().length()>0 && newLastNameTextField.getText().length()>0
           && newEmailTextField.getText().length()>0 && newPhoneTextField.getText().length()>0){

            code=newCodeTextField.getText();
            identification=newIdentificationTextField.getText();
            firstName=newFirstNameTextField.getText();
            lastName=newLastNameTextField.getText();
            email=newEmailTextField.getText();
            charge=(String)newChargeComboBox.getSelectedItem();
            typeID=(String)newTypeIDComboBox.getSelectedItem();
            phone=newPhoneTextField.getText();
            state=(String)newStateComboBox.getSelectedItem();

            int numFilas = userControl.updateUser(code, identification, firstName, lastName, email, charge, typeID, phone, state);

            System.out.println ("Filas "+ numFilas);
            if (numFilas == 1){
                JOptionPane.showMessageDialog(null, "Usuario actualizado exitosamente");
                loadEditUSer();
            }
            else {
                JOptionPane.showMessageDialog(null, "Ocurrio un problema al actualizar el Usuario");
            }
        }
        else{
                JOptionPane.showMessageDialog(null, "Por favor completa todos los campos");
        }
    }//GEN-LAST:event_editButtomActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        // TODO add your handling code here:
        EditUser editUser = new EditUser();
        editUser.setSize(639,483);
        editUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editUser);
    }//GEN-LAST:event_backButtomActionPerformed

    public void loadEditUSer(){
    
        EditUser editUser = new EditUser();
        editUser.setSize(639,483);
        editUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editUser);
}
    
    public void setValues(String code, String identification, String firstName, String lastName, String email, String charge, String typeID, String phone, String state){
        
        newCodeTextField.setText(code);
        newIdentificationTextField.setText(identification);
        newFirstNameTextField.setText(firstName);
        newLastNameTextField.setText(lastName);
        newEmailTextField.setText(email);
        newPhoneTextField.setText(phone);
        
       // newLabelCode.setVisible(false);
        newCodeTextField.setVisible(false);
        
       /* oldCodeTextField.setText(code);
        oldIdentificationTextField.setText(identification);
        oldTypeIDTextField.setText(typeID);
        oldFirstNameTextField.setText(firstName);
        oldLastNameTextField.setText(lastName);
        oldEmailTextField.setText(email);
        oldPhoneTextField.setText(phone);
        oldChargeTextField.setText(charge);
        oldStateTextField.setText(state);*/
        //stateEquipment=(String)newStateComboBox.getSelectedItem();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JButton editButtom;
    private javax.swing.JLabel editEquipmentLabel;
    private javax.swing.JLabel nameLabel14;
    private javax.swing.JLabel nameLabel15;
    private javax.swing.JLabel nameLabel16;
    private javax.swing.JLabel nameLabel17;
    private javax.swing.JLabel nameLabel18;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JComboBox<String> newChargeComboBox;
    private javax.swing.JTextField newCodeTextField;
    private javax.swing.JTextField newEmailTextField;
    private javax.swing.JTextField newFirstNameTextField;
    private javax.swing.JTextField newIdentificationTextField;
    private javax.swing.JTextField newLastNameTextField;
    private javax.swing.JTextField newPhoneTextField;
    private javax.swing.JComboBox<String> newStateComboBox;
    private javax.swing.JComboBox<String> newTypeIDComboBox;
    // End of variables declaration//GEN-END:variables
}
