/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.EquipmentControl;
import static GUI.EditEquipmentForm.newStateComboBox;
import Logic.Equipment;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class EditEquipment extends javax.swing.JPanel {
    EquipmentControl equipmentControl;

    /**
     * Creates new form EditarEquipment
     */
    public EditEquipment() {
        initComponents();
        equipmentControl = new EquipmentControl();
        loadInventory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        searchButtom = new javax.swing.JButton();
        editSelect = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipmentTable = new javax.swing.JTable();
        typeSearchCombo = new javax.swing.JComboBox<>();
        backButtom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        nameTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        searchButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SearchButtom.png"))); // NOI18N
        searchButtom.setBorderPainted(false);
        searchButtom.setContentAreaFilled(false);
        searchButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtomActionPerformed(evt);
            }
        });

        editSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarButtom.png"))); // NOI18N
        editSelect.setBorderPainted(false);
        editSelect.setContentAreaFilled(false);
        editSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSelectActionPerformed(evt);
            }
        });

        registerLabel.setBackground(new java.awt.Color(153, 153, 153));
        registerLabel.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(235, 30, 0));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarEquipoTitle.png"))); // NOI18N
        registerLabel.setAlignmentY(0.0F);
        registerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        equipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Serial", "Descripcion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipmentTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        equipmentTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(equipmentTable);

        typeSearchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Serie"}));
        typeSearchCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/VolverButtom.png"))); // NOI18N
        backButtom.setBorderPainted(false);
        backButtom.setContentAreaFilled(false);
        backButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(editSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(typeSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(typeSearchCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadInventory(){
        
    ArrayList <Object[]> inventory = new ArrayList <>();
    inventory = equipmentControl.listEquipment();
            
    DefaultTableModel modelo = (DefaultTableModel) equipmentTable.getModel();
    modelo.setRowCount(0);  

    for(int i=0; i<inventory.size(); i++ ){
    modelo.addRow(inventory.get(i));
    equipmentTable.setModel(modelo);
            }     
    }
    
    private void searchButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtomActionPerformed
        // TODO add your handling code here:
        Equipment equipment;
        String inputValue;
        String typeSearch;

        if(nameTextField.getText().length()>0){

            inputValue=nameTextField.getText();
            typeSearch=(String)typeSearchCombo.getSelectedItem();
            typeSearch = traduction(typeSearch);
            
            equipment = equipmentControl.searchEquipment(inputValue, typeSearch);

            if(equipment.getNumberEquipment()!= null){

            JOptionPane.showMessageDialog(null,"Bùsqueda Exitosa");
            listSearchEquipment(inputValue,typeSearch);
            
            }
            else{
                JOptionPane.showMessageDialog(null,"No se encontrò ningun Equipo que coincida con la bùsqueda");
                limpiar_texto();
            }
        }
            else{
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos");
            }
        
    }//GEN-LAST:event_searchButtomActionPerformed

    private void editSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSelectActionPerformed
        // TODO add your handling code here:
        
        int row = equipmentTable.getSelectedRow();
        if(row!=-1){
        EditEquipmentForm editEquipmentForm = new EditEquipmentForm();
        editEquipmentForm.setSize(639,483);
        editEquipmentForm.setLocation(0,0);
        
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editEquipmentForm);
        this.revalidate();
        this.repaint();
        
        String code=equipmentTable.getValueAt(row, 0).toString();
        String name=equipmentTable.getValueAt(row, 1).toString();
        String serial=equipmentTable.getValueAt(row, 2).toString();
        String description=equipmentTable.getValueAt(row, 3).toString();
        String state=equipmentTable.getValueAt(row, 4).toString();
        
        editEquipmentForm.setValues(code, name, serial, description, state);}
        else{ JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
        }
 
    }//GEN-LAST:event_editSelectActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        // TODO add your handling code here:
        MenuEquipment menuEquipment = new MenuEquipment();
        menuEquipment.setSize(639,483);
        menuEquipment.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(menuEquipment);
    }//GEN-LAST:event_backButtomActionPerformed
        
    public void limpiar_texto(){  
        nameTextField.setText("");    
        }
        
    public String traduction(String word){
            
            if(word.equals("Nombre")){
                word = "name";
            }
            else { word = "serialNumber";}
            
            return  word;
        }
        
    public void listSearchEquipment(String inputValue, String typeSearch){
            
            ArrayList <Object[]> inventory = new ArrayList <>();
            inventory = equipmentControl.listSearchEquipment(inputValue, typeSearch);
            
            DefaultTableModel modelo = (DefaultTableModel) equipmentTable.getModel();
            modelo.setRowCount(0);  

            for(int i=0; i<inventory.size(); i++ ){
            modelo.addRow(inventory.get(i));
            equipmentTable.setModel(modelo);
            }     
        };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JButton editSelect;
    private javax.swing.JTable equipmentTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JButton searchButtom;
    private javax.swing.JComboBox<String> typeSearchCombo;
    // End of variables declaration//GEN-END:variables
}
