/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.ProjectControl;
import Logic.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class EditProjectForm extends javax.swing.JPanel {
    ProjectControl projectControl;
    User sessionUser;

    /**
     * Creates new form EditProjectForm
     */
    public EditProjectForm(User sessionUser) {
        initComponents();
        projectControl=new ProjectControl();
        this.sessionUser=sessionUser;
        llenarCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerLabel = new javax.swing.JLabel();
        registerButtom = new javax.swing.JButton();
        newNameTextField = new javax.swing.JTextField();
        nameLabel4 = new javax.swing.JLabel();
        nameLabel5 = new javax.swing.JLabel();
        nameLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newDescriptionTextArea = new javax.swing.JTextArea();
        newManagerComboBox = new javax.swing.JComboBox<>();
        newIdentificationTextField = new javax.swing.JTextField();
        nameLabel7 = new javax.swing.JLabel();
        newCodeTextField = new javax.swing.JTextField();
        codeTitle = new javax.swing.JLabel();
        nameLabel11 = new javax.swing.JLabel();
        newStateComboBox = new javax.swing.JComboBox<>();
        backButtom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        registerLabel.setBackground(new java.awt.Color(153, 153, 153));
        registerLabel.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(235, 30, 0));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarProyectoTitle.png"))); // NOI18N
        registerLabel.setAlignmentY(0.0F);
        registerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        registerButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GuardarButtom.png"))); // NOI18N
        registerButtom.setBorderPainted(false);
        registerButtom.setContentAreaFilled(false);
        registerButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtomActionPerformed(evt);
            }
        });

        newNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        nameLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel4.setText("Nombre");

        nameLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel5.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel5.setText("Descripcion");

        nameLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel6.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel6.setText("Lider");

        newDescriptionTextArea.setColumns(20);
        newDescriptionTextArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        newDescriptionTextArea.setRows(5);
        newDescriptionTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newDescriptionTextArea.setLineWrap(true);
        newDescriptionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(newDescriptionTextArea);

        newManagerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        newManagerComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        newIdentificationTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        nameLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel7.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel7.setText("Identificacion");

        newCodeTextField.setEditable(false);
        newCodeTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        codeTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle.setText("Codigo");

        nameLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel11.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel11.setText("Estado");

        newStateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Activo","Inactivo","Suspendido"}));
        newStateComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newStateComboBox.setPreferredSize(new java.awt.Dimension(28, 28));

        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CancelarButton.png"))); // NOI18N
        backButtom.setBorderPainted(false);
        backButtom.setContentAreaFilled(false);
        backButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLabel7)
                                    .addComponent(nameLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newNameTextField)
                                    .addComponent(newIdentificationTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLabel6)
                                    .addComponent(nameLabel5)
                                    .addComponent(nameLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(newStateComboBox, 0, 208, Short.MAX_VALUE)
                                            .addComponent(newManagerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(codeTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newIdentificationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newManagerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtomActionPerformed
        // TODO add your handling code here:
        String code;
        String identification;
        String name;
        String description;
        String managerID;
        String state;

        if(newIdentificationTextField.getText().length()>0 && newNameTextField.getText().length()>0 && newDescriptionTextArea.getText().length()>0){

            code=newCodeTextField.getText();
            identification=newIdentificationTextField.getText();
            name=newNameTextField.getText();
            description=newDescriptionTextArea.getText();
            managerID = projectControl.getManagerID((String)newManagerComboBox.getSelectedItem());
            state=(String)newStateComboBox.getSelectedItem();

            int numFilas = projectControl.updateProject(code, identification, name, description, managerID,state);

            System.out.println ("Filas "+ numFilas);
            if (numFilas == 1){

                JOptionPane.showMessageDialog(null, "Proyecto guardado exitosamente");
                loadEditProject();
            }
            else {
                JOptionPane.showMessageDialog(null, "Ocurrio un problema al guardar el Proyecto");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos");
        }
    }//GEN-LAST:event_registerButtomActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        // TODO add your handling code here:
        EditProject editProject = new EditProject(sessionUser);
        editProject.setSize(639,483);
        editProject.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editProject);
    }//GEN-LAST:event_backButtomActionPerformed

    public void setValues(String code, String identification, String name, String description, String manager, String state){
        
        newCodeTextField.setText(code);
        newCodeTextField.setVisible(false);
        codeTitle.setVisible(false);
        
        newIdentificationTextField.setText(identification);
        newNameTextField.setText(name);
        newDescriptionTextArea.setText(description);
        
       /* oldCodeTextField.setText(code);
        oldIdentificationTextField.setText(identification);
        oldNameTextField.setText(name);
        oldDescriptionTextArea.setText(description);
        oldManagerTextField.setText(manager);
        oldStateTextField.setText(state);*/
        //stateEquipment=(String)newStateComboBox.getSelectedItem();
        
    }

    public void llenarCB(){
      newManagerComboBox.removeAllItems(); //Vaciamos el JComboBox
      ArrayList <String> managers = new ArrayList<String>();
      managers = projectControl.loadManager();//La consulta tiene que retornar un ArrayList

      for(int i=0; i<managers.size();i++){
      newManagerComboBox.addItem(managers.get(i));
    }
}
    
    public void loadEditProject(){
        
        EditProject editProject = new EditProject(sessionUser);
        editProject.setSize(639,483);
        editProject.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editProject);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel codeTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel11;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel nameLabel6;
    private javax.swing.JLabel nameLabel7;
    private javax.swing.JTextField newCodeTextField;
    public static javax.swing.JTextArea newDescriptionTextArea;
    private javax.swing.JTextField newIdentificationTextField;
    private javax.swing.JComboBox<String> newManagerComboBox;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JComboBox<String> newStateComboBox;
    private javax.swing.JButton registerButtom;
    private javax.swing.JLabel registerLabel;
    // End of variables declaration//GEN-END:variables
}
