/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.ReserveControl;
import Logic.Reserve;
import Logic.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class ListReservation extends javax.swing.JPanel {
        ReserveControl reserveControl;
        User sessionUser;

    /**
     * Creates new form ListAllReservation
     */
    public ListReservation(User sessionUser) {
        reserveControl = new ReserveControl();
        this.sessionUser=sessionUser;
        initComponents();
        loadReserves();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reserveTable = new javax.swing.JTable();
        showInfoReserve = new javax.swing.JButton();
        searchButtom = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        typeSearchCombo = new javax.swing.JComboBox<>();
        backButtom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ReserveTitle.png"))); // NOI18N

        reserveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Reserva", "Usuario", "Articulo", "Fecha Inicial", "Fecha Final", "Fecha Prestamo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reserveTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        reserveTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(reserveTable);

        showInfoReserve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/VerInfoButtom.png"))); // NOI18N
        showInfoReserve.setBorderPainted(false);
        showInfoReserve.setContentAreaFilled(false);
        showInfoReserve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showInfoReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInfoReserveActionPerformed(evt);
            }
        });

        searchButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SearchButtom.png"))); // NOI18N
        searchButtom.setBorderPainted(false);
        searchButtom.setContentAreaFilled(false);
        searchButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtomActionPerformed(evt);
            }
        });

        nameTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        typeSearchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo","Usuario","Articulo", "Estado"}));
        typeSearchCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/VolverButtom.png"))); // NOI18N
        backButtom.setBorderPainted(false);
        backButtom.setContentAreaFilled(false);
        backButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtom.setPreferredSize(new java.awt.Dimension(45, 45));
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(typeSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(showInfoReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(searchButtom))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(showInfoReserve)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtomActionPerformed
        // TODO add your handling code here:
        Reserve reserve;
        String inputValue;
        String typeSearch;

        if(nameTextField.getText().length()>0){

            inputValue=nameTextField.getText();
            typeSearch=(String)typeSearchCombo.getSelectedItem();
            typeSearch = traduction(typeSearch);

            reserve = reserveControl.searchReserve(inputValue, typeSearch);
            if(reserve.getCode()!= null){
                JOptionPane.showMessageDialog(null,"Bùsqueda Exitosa");
                listSearchReserve(inputValue,typeSearch);
            }
            else{
                JOptionPane.showMessageDialog(null,"No se encontrò ninguna Reserva que coincida con la bùsqueda");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos");
        }
    }//GEN-LAST:event_searchButtomActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        // TODO add your handling code here:
        MenuLoan menuLoan = new MenuLoan(sessionUser);
        menuLoan.setSize(639,483);
        menuLoan.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(menuLoan);
    }//GEN-LAST:event_backButtomActionPerformed

    private void showInfoReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInfoReserveActionPerformed
        // TODO add your handling code here:
        int row = reserveTable.getSelectedRow();
        if(row!=-1){
        ShowInfoReserve  showInfoReserve= new ShowInfoReserve(sessionUser);
        showInfoReserve.setSize(639,494);
        showInfoReserve.setLocation(0,0);
        
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(showInfoReserve);
        
        
        String code=reserveTable.getValueAt(row, 0).toString();
        String nameUser=reserveTable.getValueAt(row, 1).toString();
        String nameEquipment=reserveTable.getValueAt(row, 2).toString();
        
        showInfoReserve.setValues(code, nameUser, nameEquipment);
        }
        else{ JOptionPane.showMessageDialog(null, "Por favor Seleccione una Fila");
       }
        
    }//GEN-LAST:event_showInfoReserveActionPerformed

    public void loadReserves(){
        
        ArrayList <Object[]> Reserves = new ArrayList <>();
        Reserves = reserveControl.listReserves();

        DefaultTableModel modelo = (DefaultTableModel) reserveTable.getModel();
        modelo.setRowCount(0);  

        for(int i=0; i<Reserves.size(); i++ ){
            modelo.addRow(Reserves.get(i));
            reserveTable.setModel(modelo);
        }     
    }
    
    public String traduction(String word){
        switch (word) {
            case "Codigo":
             word = "code";
             break;
             case "Articulo":
             word = "equipment.name";
             break;
             case "Usuario":
             word = "member.name";
             break;
             case "Estado":
             word = "state";
             break;
             default:
             System.out.println("error");
             break;} 
             
             return  word;
        }
    
    public void listSearchReserve(String inputValue, String typeSearch){
            
        ArrayList <Object[]> reserves = new ArrayList <>();
        reserves = reserveControl.listSearchReserve(inputValue, typeSearch);

        DefaultTableModel modelo = (DefaultTableModel) reserveTable.getModel();
        modelo.setRowCount(0);  

        for(int i=0; i<reserves.size(); i++ ){
        modelo.addRow(reserves.get(i));
        reserveTable.setModel(modelo);
            }     
        }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable reserveTable;
    private javax.swing.JButton searchButtom;
    private javax.swing.JButton showInfoReserve;
    private javax.swing.JComboBox<String> typeSearchCombo;
    // End of variables declaration//GEN-END:variables
}
