/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class MainMenuAdministrador extends javax.swing.JFrame {
    User sessionUser;

    /**
     * Creates new form MainMenu
     */
    public MainMenuAdministrador(User sessionUser) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("SIMPLE");
        this.sessionUser = sessionUser;
        displayMenuUser(sessionUser.getCharge());
        
    }
    
    private void displayMenuUser(String userCharge){
        switch (userCharge) {
        case "Administrador":
        myProfileButtom.setVisible(true);
        userButtom.setVisible(true);
        EquipmentButtom.setVisible(true);
        projectButtom.setVisible(true);
        loanButtom.setVisible(true);
        break;
        case "Miembro":
        myProfileButtom.setVisible(true);
        userButtom.setVisible(true);
        EquipmentButtom.setVisible(true);
        projectButtom.setVisible(true);
        loanButtom.setVisible(true);
        break;
        case "Coordinador de Equipos":
        myProfileButtom.setVisible(true);
        userButtom.setVisible(true);
        EquipmentButtom.setVisible(true);
        projectButtom.setVisible(true);
        loanButtom.setVisible(true);
        break;
        case "Lider de Proyecto":
        myProfileButtom.setVisible(true);
        userButtom.setVisible(true);
        EquipmentButtom.setVisible(true);
        projectButtom.setVisible(true);
        loanButtom.setVisible(true);
        break;
        case "Director de Laboratorio":
        myProfileButtom.setVisible(true);
        userButtom.setVisible(true);
        EquipmentButtom.setVisible(true);
        projectButtom.setVisible(true);
        loanButtom.setVisible(true);
        break;
        default:
        System.out.println("error" );
        break;}       
    }

    private MainMenuAdministrador() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        panelImage6 = new org.edisoncor.gui.panel.PanelImage();
        logOutButtom = new javax.swing.JButton();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();
        EquipmentButtom = new javax.swing.JButton();
        projectButtom = new javax.swing.JButton();
        loanButtom = new javax.swing.JButton();
        myProfileButtom = new javax.swing.JButton();
        userButtom = new javax.swing.JButton();
        PanelDerecha = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImage2.setBackground(new java.awt.Color(255, 255, 255));
        panelImage2.setForeground(new java.awt.Color(255, 255, 255));
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondoBlanco.png"))); // NOI18N

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Panel superior.png"))); // NOI18N

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SimpleMainMenu.png"))); // NOI18N

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Univalle.png"))); // NOI18N

        javax.swing.GroupLayout panelImage6Layout = new javax.swing.GroupLayout(panelImage6);
        panelImage6.setLayout(panelImage6Layout);
        panelImage6Layout.setHorizontalGroup(
            panelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        panelImage6Layout.setVerticalGroup(
            panelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        logOutButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cerrarsesion.png"))); // NOI18N
        logOutButtom.setBorderPainted(false);
        logOutButtom.setContentAreaFilled(false);
        logOutButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(panelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(logOutButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(logOutButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panel izquierdo.png"))); // NOI18N

        buttonIcon1.setBackground(new java.awt.Color(255, 255, 255));
        buttonIcon1.setBorder(null);
        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonusarios.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");

        EquipmentButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EquiposMainMenu.png"))); // NOI18N
        EquipmentButtom.setBorderPainted(false);
        EquipmentButtom.setContentAreaFilled(false);
        EquipmentButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EquipmentButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentButtomActionPerformed(evt);
            }
        });

        projectButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Proyecto.png"))); // NOI18N
        projectButtom.setBorderPainted(false);
        projectButtom.setContentAreaFilled(false);
        projectButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        projectButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectButtomActionPerformed(evt);
            }
        });

        loanButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PrestamosMainMenu.png"))); // NOI18N
        loanButtom.setBorderPainted(false);
        loanButtom.setContentAreaFilled(false);
        loanButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loanButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanButtomActionPerformed(evt);
            }
        });

        myProfileButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PerfilMainMenu.png"))); // NOI18N
        myProfileButtom.setBorderPainted(false);
        myProfileButtom.setContentAreaFilled(false);
        myProfileButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myProfileButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtomActionPerformed(evt);
            }
        });

        userButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UsuarioMainMenu.png"))); // NOI18N
        userButtom.setBorderPainted(false);
        userButtom.setContentAreaFilled(false);
        userButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myProfileButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userButtom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(EquipmentButtom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(projectButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loanButtom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1213, 1213, 1213)
                .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage3Layout.createSequentialGroup()
                .addGroup(panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage3Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(myProfileButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EquipmentButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(projectButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loanButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDerecha.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoTeam.png"))); // NOI18N

        javax.swing.GroupLayout PanelDerechaLayout = new javax.swing.GroupLayout(PanelDerecha);
        PanelDerecha.setLayout(PanelDerechaLayout);
        PanelDerechaLayout.setHorizontalGroup(
            PanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechaLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDerechaLayout.setVerticalGroup(
            PanelDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechaLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addComponent(panelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EquipmentButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentButtomActionPerformed
        // TODO add your handling code here:

        MenuEquipment menuEquipment = new MenuEquipment(sessionUser);
        menuEquipment.setSize(639,483);
        menuEquipment.setLocation(0,50);

        PanelDerecha.removeAll();
        PanelDerecha.revalidate();
        PanelDerecha.repaint();
        PanelDerecha.add(menuEquipment);
    }//GEN-LAST:event_EquipmentButtomActionPerformed

    private void userButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtomActionPerformed
        // TODO add your handling code here:

        MenuUser menuUser = new MenuUser(sessionUser);
        menuUser.setSize(639,483);
        menuUser.setLocation(0,50);

        PanelDerecha.removeAll();
        PanelDerecha.revalidate();
        PanelDerecha.repaint();
        PanelDerecha.add(menuUser);
    }//GEN-LAST:event_userButtomActionPerformed

    private void projectButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectButtomActionPerformed
        // TODO add your handling code here:
        MenuProject menuProject = new MenuProject(sessionUser);
        menuProject.setSize(639,483);
        menuProject.setLocation(0,50);

        PanelDerecha.removeAll();
        PanelDerecha.revalidate();
        PanelDerecha.repaint();
        PanelDerecha.add(menuProject);
    }//GEN-LAST:event_projectButtomActionPerformed

    private void loanButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanButtomActionPerformed
        // TODO add your handling code here:
        MenuLoan menuLoan = new MenuLoan(sessionUser);
        menuLoan.setSize(639,483);
        menuLoan.setLocation(0,50);

        PanelDerecha.removeAll();
        PanelDerecha.revalidate();
        PanelDerecha.repaint();
        PanelDerecha.add(menuLoan);
    }//GEN-LAST:event_loanButtomActionPerformed

    private void myProfileButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtomActionPerformed
        // TODO add your handling code here:
        MenuProfile menuProfile = new MenuProfile(sessionUser);
        menuProfile.setSize(639,483);
        menuProfile.setLocation(0,50);

        PanelDerecha.removeAll();
        PanelDerecha.revalidate();
        PanelDerecha.repaint();
        PanelDerecha.add(menuProfile);
    }//GEN-LAST:event_myProfileButtomActionPerformed

    private void logOutButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtomActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Adiós, que tengas un buen día"); 

        Login login = new Login();
        this.dispose();
        login.setVisible(true);
        
    }//GEN-LAST:event_logOutButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EquipmentButtom;
    private javax.swing.JPanel PanelDerecha;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loanButtom;
    private javax.swing.JButton logOutButtom;
    private javax.swing.JButton myProfileButtom;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage6;
    private javax.swing.JButton projectButtom;
    private javax.swing.JButton userButtom;
    // End of variables declaration//GEN-END:variables
}
