/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Diego
 */
public class MenuUser extends javax.swing.JPanel {

    /**
     * Creates new form MenuUser
     */
    public MenuUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisterUserButtom = new javax.swing.JButton();
        listUserButtom = new javax.swing.JButton();
        editUserButtom = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        RegisterUserButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RegisterUser.png"))); // NOI18N
        RegisterUserButtom.setBorderPainted(false);
        RegisterUserButtom.setContentAreaFilled(false);
        RegisterUserButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterUserButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUserButtomActionPerformed(evt);
            }
        });

        listUserButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ListUser.png"))); // NOI18N
        listUserButtom.setBorderPainted(false);
        listUserButtom.setContentAreaFilled(false);
        listUserButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listUserButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUserButtomActionPerformed(evt);
            }
        });

        editUserButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditUser.png"))); // NOI18N
        editUserButtom.setBorderPainted(false);
        editUserButtom.setContentAreaFilled(false);
        editUserButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(listUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(editUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(RegisterUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(RegisterUserButtom)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterUserButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUserButtomActionPerformed
        // TODO add your handling code here:

        RegisterUser registerUser = new RegisterUser();
        registerUser.setSize(639,483);
        registerUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(registerUser);

    }//GEN-LAST:event_RegisterUserButtomActionPerformed

    private void listUserButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUserButtomActionPerformed
        // TODO add your handling code here:

        ListUser listUser = new ListUser();
        listUser.setSize(639,483);
        listUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(listUser);
    }//GEN-LAST:event_listUserButtomActionPerformed

    private void editUserButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtomActionPerformed
        // TODO add your handling code here:

        EditUser editUser = new EditUser();
        editUser.setSize(639,483);
        editUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editUser);

    }//GEN-LAST:event_editUserButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterUserButtom;
    private javax.swing.JButton editUserButtom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listUserButtom;
    // End of variables declaration//GEN-END:variables
}
