/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.User;

/**
 *
 * @author Diego
 */
public class MenuProfile extends javax.swing.JPanel {
    User sessionUser;
    /**
     * Creates new form MenuPerfil
     */
    public MenuProfile(User sessionUser) {
        initComponents();
        this.sessionUser=sessionUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showProfile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        EditPerfilButtom = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        showProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PerfilButtom.png"))); // NOI18N
        showProfile.setBorderPainted(false);
        showProfile.setContentAreaFilled(false);
        showProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showProfile.setPreferredSize(new java.awt.Dimension(130, 130));
        showProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProfileActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 30, 0));
        jLabel4.setText("Mi Perfil");

        EditPerfilButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarUsuarioButtom.png"))); // NOI18N
        EditPerfilButtom.setBorderPainted(false);
        EditPerfilButtom.setContentAreaFilled(false);
        EditPerfilButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditPerfilButtom.setPreferredSize(new java.awt.Dimension(130, 130));
        EditPerfilButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPerfilButtomActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 30, 0));
        jLabel7.setText("Editar Perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16))
                    .addComponent(showProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(EditPerfilButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(showProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EditPerfilButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProfileActionPerformed
        // TODO add your handling code here:

        String code = sessionUser.getCode();
        String identification = sessionUser.getIdentification();
        String firstName = sessionUser.getFirstName();
        String lastName = sessionUser.getLastName();
        String email = sessionUser.getEmail();
        String charge = sessionUser.getCharge();
        String typeID = sessionUser.getTypeID();
        String phone = sessionUser.getPhone();
        String state = sessionUser.getState();

        ShowInfoProfile showInfoProfile = new ShowInfoProfile(sessionUser);
        showInfoProfile.setSize(639,494);
        showInfoProfile.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(showInfoProfile);

        showInfoProfile.setValues(code, identification, firstName, lastName, email, charge, typeID, phone, state);
    }//GEN-LAST:event_showProfileActionPerformed

    private void EditPerfilButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPerfilButtomActionPerformed
        // TODO add your handling code here:
        
        EditProfileForm editProfileForm = new EditProfileForm(sessionUser);
        editProfileForm.setSize(639,483);
        editProfileForm.setLocation(0,0);
        
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editProfileForm);   
        
    }//GEN-LAST:event_EditPerfilButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditPerfilButtom;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton showProfile;
    // End of variables declaration//GEN-END:variables
}
