/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Login;
import Controller.UserControl;
import Logic.User;
import sun.security.x509.X500Name;

/**
 *
 * @author Diego
 */
public class MenuUser extends javax.swing.JPanel {
    UserControl userControl;
    User sessionUser;
    

    /**
     * Creates new form MenuUser
     */
    public MenuUser(User sessionUser) {
        initComponents();
        this.sessionUser = sessionUser;
        displayMenu(sessionUser.getCharge());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listUserButtom = new javax.swing.JButton();
        editUserButtom = new javax.swing.JButton();
        RegisterUserButtom = new javax.swing.JButton();
        listLabel = new javax.swing.JLabel();
        editLabel = new javax.swing.JLabel();
        registerlabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        listUserButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ListarUsuarioButtom.png"))); // NOI18N
        listUserButtom.setBorderPainted(false);
        listUserButtom.setContentAreaFilled(false);
        listUserButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listUserButtom.setPreferredSize(new java.awt.Dimension(130, 130));
        listUserButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUserButtomActionPerformed(evt);
            }
        });

        editUserButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/EditarUsuarioButtom.png"))); // NOI18N
        editUserButtom.setBorderPainted(false);
        editUserButtom.setContentAreaFilled(false);
        editUserButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editUserButtom.setMaximumSize(new java.awt.Dimension(130, 130));
        editUserButtom.setMinimumSize(new java.awt.Dimension(130, 130));
        editUserButtom.setName(""); // NOI18N
        editUserButtom.setPreferredSize(new java.awt.Dimension(130, 130));
        editUserButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtomActionPerformed(evt);
            }
        });

        RegisterUserButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/RegistrarUsuarioButtom.png"))); // NOI18N
        RegisterUserButtom.setBorderPainted(false);
        RegisterUserButtom.setContentAreaFilled(false);
        RegisterUserButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterUserButtom.setPreferredSize(new java.awt.Dimension(130, 130));
        RegisterUserButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUserButtomActionPerformed(evt);
            }
        });

        listLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        listLabel.setForeground(new java.awt.Color(235, 30, 0));
        listLabel.setText("Listar Usuarios");

        editLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        editLabel.setForeground(new java.awt.Color(235, 30, 0));
        editLabel.setText("Editar Usuarios");

        registerlabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registerlabel.setForeground(new java.awt.Color(235, 30, 0));
        registerlabel.setText("Registrar Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listUserButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editLabel))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerlabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(RegisterUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listLabel)
                    .addComponent(editLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(RegisterUserButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerlabel)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void displayMenu(String userCharge){
        switch (userCharge) {
        case "Administrador":
        listUserButtom.setVisible(true);
        editUserButtom.setVisible(true);
        RegisterUserButtom.setVisible(true);
        break;
        case "Miembro":
        listUserButtom.setVisible(true);
        editUserButtom.setVisible(false);
        editLabel.setVisible(false);
        RegisterUserButtom.setVisible(false);
        registerlabel.setVisible(false);
        break;
        case "Coordinador de Equipos":
        listUserButtom.setVisible(true);
        editUserButtom.setVisible(false);
        editLabel.setVisible(false);
        RegisterUserButtom.setVisible(false);
        registerlabel.setVisible(false);
        break;
        case "Lider de Proyecto":
        listUserButtom.setVisible(true);
        editUserButtom.setVisible(false);
        editLabel.setVisible(false);
        RegisterUserButtom.setVisible(false);
        registerlabel.setVisible(false);
        break;
        case "Director de Laboratorio":
        listUserButtom.setVisible(true);
        editUserButtom.setVisible(true);
        RegisterUserButtom.setVisible(true);
        break;
        default:
        System.out.println("error" );
        break;}      
}
    
    
    private void RegisterUserButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUserButtomActionPerformed
        // TODO add your handling code here:

        RegisterUser registerUser = new RegisterUser(sessionUser);
        registerUser.setSize(639,483);
        registerUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(registerUser);

    }//GEN-LAST:event_RegisterUserButtomActionPerformed

    private void listUserButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUserButtomActionPerformed
        // TODO add your handling code here:

        ListUser listUser = new ListUser(sessionUser);
        listUser.setSize(639,483);
        listUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(listUser);
    }//GEN-LAST:event_listUserButtomActionPerformed

    private void editUserButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtomActionPerformed
        // TODO add your handling code here:

        EditUser editUser = new EditUser(sessionUser);
        editUser.setSize(639,483);
        editUser.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(editUser);

    }//GEN-LAST:event_editUserButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterUserButtom;
    private javax.swing.JLabel editLabel;
    private javax.swing.JButton editUserButtom;
    private javax.swing.JLabel listLabel;
    private javax.swing.JButton listUserButtom;
    private javax.swing.JLabel registerlabel;
    // End of variables declaration//GEN-END:variables
}
