/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.LoanControl;
import Logic.Loan;
import Logic.User;
import java.awt.ComponentOrientation;
import java.text.Format;
import java.text.SimpleDateFormat;

/**
 *
 * @author Diego
 */
public class ShowInfoLoan extends javax.swing.JPanel {
    User sessionUser;
    LoanControl loanControl;
    /**
     * Creates new form ShowLoanInfo
     */
    public ShowInfoLoan(User sessionUser) {
        initComponents();
        loanControl = new LoanControl();
        this.sessionUser=sessionUser;
    }
    
public void setValues(String code, String nameUser, String nameEquipment){
        Loan loan = new Loan();
        
        String startDate;
        String finalDate;
        String deliverDate;
        
        loan = loanControl.getInfoLoan(code);
        Format formatter = new SimpleDateFormat("yyyy-MM-dd");
        
        if(loan.getStartDate() != null){
        startDate = formatter.format(loan.getStartDate());
        finalDate = formatter.format(loan.getFinalDate());
        }
        else{startDate="";
             finalDate="";
             deliverDate="";      
        }
        
        if(loan.returnEquipment() != null){
        deliverDate = formatter.format(loan.returnEquipment());
        }
        else {deliverDate="";
        }
        
        String renew=Integer.toString(loan.getRenew());
      
        codeText.setText(loan.getCode());
        userNameText.setText(nameUser);
        userIDText.setText(loan.getUserCode());
        equipmentNameText.setText(nameEquipment);
        equipmentIDText.setText(loan.getEquipmentCode());
        startDateText.setText(startDate);
        finalDateText.setText(finalDate);
        deliverDateText.setText(deliverDate);
        stateText.setText(loan.getState());
        renewText.setText(renew);
            
        
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codeTitle = new javax.swing.JLabel();
        codeText = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        userNameText = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        userIDText = new javax.swing.JLabel();
        codeTitle3 = new javax.swing.JLabel();
        equipmentNameText = new javax.swing.JLabel();
        codeTitle4 = new javax.swing.JLabel();
        equipmentIDText = new javax.swing.JLabel();
        codeTitle5 = new javax.swing.JLabel();
        startDateText = new javax.swing.JLabel();
        codeTitle6 = new javax.swing.JLabel();
        finalDateText = new javax.swing.JLabel();
        codeTitle7 = new javax.swing.JLabel();
        deliverDateText = new javax.swing.JLabel();
        codeTitle8 = new javax.swing.JLabel();
        stateText = new javax.swing.JLabel();
        backButtom = new javax.swing.JButton();
        codeTitle9 = new javax.swing.JLabel();
        renewText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/InfoPrestamosTitle.png"))); // NOI18N

        codeTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle.setText("Codigo Prestamo:");

        codeText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(235, 30, 0));
        nameLabel.setText("Nombre Usuario:");

        userNameText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        userIDLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        userIDLabel.setForeground(new java.awt.Color(235, 30, 0));
        userIDLabel.setText("Usuario ID:");

        userIDText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        codeTitle3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle3.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle3.setText("Articulo:");

        equipmentNameText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        codeTitle4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle4.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle4.setText("Numero Serie:");

        equipmentIDText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        codeTitle5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle5.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle5.setText("Fecha Inicial:");

        startDateText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        codeTitle6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle6.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle6.setText("Fecha Final:");

        finalDateText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        codeTitle7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle7.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle7.setText("Fecha Entrega:");

        deliverDateText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        codeTitle8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle8.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle8.setText("Estado:");

        stateText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        backButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/VolverButtom.png"))); // NOI18N
        backButtom.setBorderPainted(false);
        backButtom.setContentAreaFilled(false);
        backButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButtom.setPreferredSize(new java.awt.Dimension(45, 45));
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        codeTitle9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        codeTitle9.setForeground(new java.awt.Color(235, 30, 0));
        codeTitle9.setText("Renovaciones:");

        renewText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(codeTitle3)
                                    .addComponent(userIDLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(codeTitle7)
                                    .addComponent(codeTitle6)
                                    .addComponent(codeTitle5)
                                    .addComponent(codeTitle4)
                                    .addComponent(codeTitle8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equipmentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equipmentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finalDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deliverDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(codeTitle9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(renewText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(equipmentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTitle3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(equipmentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTitle4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTitle5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finalDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTitle6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deliverDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeTitle7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeTitle8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(renewText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeTitle9))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        // TODO add your handling code here:
        
        ListLoan listLoan = new ListLoan(sessionUser);
        listLoan.setSize(639,483);
        listLoan.setLocation(0,0);

        this.removeAll();
        this.revalidate();
        this.repaint();
        this.add(listLoan);
    }//GEN-LAST:event_backButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel codeText;
    private javax.swing.JLabel codeTitle;
    private javax.swing.JLabel codeTitle3;
    private javax.swing.JLabel codeTitle4;
    private javax.swing.JLabel codeTitle5;
    private javax.swing.JLabel codeTitle6;
    private javax.swing.JLabel codeTitle7;
    private javax.swing.JLabel codeTitle8;
    private javax.swing.JLabel codeTitle9;
    private javax.swing.JLabel deliverDateText;
    private javax.swing.JLabel equipmentIDText;
    private javax.swing.JLabel equipmentNameText;
    private javax.swing.JLabel finalDateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel renewText;
    private javax.swing.JLabel startDateText;
    private javax.swing.JLabel stateText;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JLabel userIDText;
    private javax.swing.JLabel userNameText;
    // End of variables declaration//GEN-END:variables
}
